MusicStore.WebApp/Models/ItemTypeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MusicStore.WebApp.Models
{
    public class ItemTypeViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "TypeReqired")]
        public string Type { get; set; }
    }
}

MusicStore.WebApp/Controllers/ItemTypeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MusicStore.Business.Interfaces;
using MusicStore.Data.Models;
using MusicStore.WebApp.Models;


namespace MusicStore.WebApp.Controllers
{
    public class ItemTypeController : Controller
    {
        private readonly IItemTypeService _typeService;

        public ItemTypeController(IItemTypeService typeService)
        {
            _typeService = typeService;
        }
        [HttpGet("[controller]")]
        public IActionResult Types()
        {
           return View();
        }
        
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Types([FromBody]DtQuery query)
        {
            var types =  await _typeService.GetAllTypes(query);
            return Json(types);
        }
        
        [Authorize(Roles = "Admin")]
        public  IActionResult AddType()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
       
        public async Task<IActionResult> AddTypePost(ItemTypeViewModel typeDto)
        {
            if (!ModelState.IsValid) return View("AddType");
            var type = new ItemType()
            {
                Type = typeDto.Type
            };
            await _typeService.CreateType(type);
            return Redirect("/ItemType/");
        }
        
        [HttpGet("[controller]/{typeId}/[action]")]   
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditType([FromRoute] int typeId)
        {
            var type = await _typeService.GetType(typeId);
            var itemView = new ItemTypeViewModel()
            {
                Id = type.Id,
                Type = type.Type
            };
            return View(itemView);
        }
        
        [HttpPost("")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditTypePost(ItemTypeViewModel typeDto)
        {
            if (ModelState.IsValid)
            {
                var type = new ItemType()
                {
                    Id = typeDto.Id,
                    Type = typeDto.Type
                };
                await _typeService.UpdateType(type);
                return Redirect("/ItemType/");
            }
            ViewBag.Message = string.Format("Input error!");
            return View("EditType");
        }
        [HttpDelete("[controller]/{typeId}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteType([FromRoute]int typeId)
        {
            await _typeService.RemoveType(typeId);
            return Ok();
        }
    }
}

MusicStore.WebApp/Views/ItemType/AddType.cshtml
@model MusicStore.WebApp.Models.ItemTypeViewModel
@{
    Layout = null;
}
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">@Localizer["New Type"]</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <form asp-action="AddTypePost" method="post">
                <div class="form-group">
                    <label for="Type">@Localizer["New Type"]</label>
                    <input name="Type" id="Type" class="form-control" asp-for="Type" placeholder="@Localizer["Enter type"]"/>
                    <span asp-validation-for="Type"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["Cancel"]</button>
                    <button type="submit" class="btn btn-primary">@Localizer["Add"]</button>
                </div>
            </form>
        </dl>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

MusicStore.WebApp/Views/ItemType/EditType.cshtml
@model MusicStore.WebApp.Models.ItemTypeViewModel
@{
    Layout = null;    
}
@using (Html.BeginForm("EditTypePost", "ItemType", FormMethod.Post, new {enctype = "multipart/form-data"})) {
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">@Localizer["Edit Type"]</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <form action="" method="post">

                <div class="form-group">
                    <label for="exampleInputEmail1">@Localizer["Name"]</label>
                    <input type="text" id="exampleInputEmail1" class="form-control" placeholder="@Localizer["Enter type"]" asp-for="Type">
                    <span asp-validation-for="Type"></span>

                </div>

                @Html.HiddenFor(model => model.Id)
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["Cancel"]</button>
                    <button type="submit" class="btn btn-primary">@Localizer["Submit"]</button>
                </div>
            </form>
        </dl>
    </div>
</div>
}
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

MusicStore.WebApp/Views/ItemType/Types.cshtml
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="my-2 p-4 bg-white rounded shadow-lg">
                <div class="row align-content-center mb-3">
                    <div class="col-4 my-auto">
                        <h5 class="mb-0">@Localizer["List of types"]</h5>
                    </div>
                </div>

                <table id="item-type-tbl" class="table"></table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteItemModal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete type</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button id="deleteItemBtn" type="button" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <div id="editItemTypeModal" class="modal" tabindex="-1">
        <div class="modal-dialog" id="editContent">
        </div>
    </div>

@section Scripts
{
    <script asp-append-version="true" src="~/js/types.js"></script>
    <script>
     const name = '@Html.Raw(Localizer.GetString("Name"))';
        const edit = '@Html.Raw(Localizer.GetString("Edit"))';
        const deleteField = '@Html.Raw(Localizer.GetString("Delete"))';
        const search = '@Html.Raw(Localizer.GetString("Search")):';
        const previous = '@Html.Raw(Localizer.GetString("Previous"))';
        const next = '@Html.Raw(Localizer.GetString("Next"))';
        const showing = '@Html.Raw(Localizer.GetString("Showing"))';
        const of = '@Html.Raw(Localizer.GetString("of"))';
        const to = '@Html.Raw(Localizer.GetString("to"))';
        const entries = '@Html.Raw(Localizer.GetString("entries"))';
        const confirmDelete = '@Html.Raw(Localizer.GetString("Are you sure you want to delete with"))'
        const translateTable = {
            name : name, 
            edit : edit, 
            deleteField : deleteField,
            search : search,
            previous: previous,
            showing: showing,
            next : next,
            "of" : of, 
            to: to, 
            entries: entries,
            confirmDelete: confirmDelete
        }
        $(document).ready( function () {
            const typesController = GetTypesController(translateTable);
            typesController.init();
            
             $(".compItem").click(function (e) {
                                e.preventDefault();
                                $.get(this.href, function (data) {
                                    $('#dialogContent').html(data);
                                    $('#addItemModal').modal('show');
                                });
                            });
        });
     
    </script>
}