MusicStore.WebApp/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicStore.Business.Interfaces;
using MusicStore.WebApp.Helpers;
using MusicStore.WebApp.Models;
using X.PagedList;
using Item = MusicStore.Data.Models.Item;


namespace MusicStore.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ItemController : Controller
    {
        private readonly IItemService _itemService;
        private readonly IWebHostEnvironment _webHostEnvironment;
   

        public ItemController(IItemService itemService,  IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _itemService = itemService;
        }
        [HttpGet]
        public IActionResult Items()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetExcel()
        {
            var products = _itemService.GetAllItems();
            var productList = new List<ItemViewModel>();
            productList.AddRange(products.Select(x => new ItemViewModel()
            {
                Name = x.Name,
                Price = x.Price,
                Description = x.Description
            }));

            using var workbook = new XLWorkbook(XLEventTracking.Disabled);
            var worksheet = workbook.Worksheets.Add("Products");

            worksheet.Cell("A1").Value = "Название";
            worksheet.Cell("B1").Value = "Цена";

            worksheet.Range("A1:B1").Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            worksheet.Row(1).Style.Font.Bold = true;

            for (var i = 0; i < productList.Count; i++)
            {
                worksheet.Range($"A{i + 2}:B{i + 2}").Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                worksheet.Cell(i + 2, 1).Value = productList[i].Name;
                worksheet.Cell(i + 2, 2).Value = productList[i].Price;

            }

            worksheet.ColumnWidth = 30;
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            stream.Flush();

            return new FileContentResult(stream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
            {
                FileDownloadName = $"products_{DateTime.UtcNow.ToShortDateString()}.xlsx"
            };
        }

        [HttpPost]
        public async Task<IActionResult> List([FromBody]DtQuery query)
        {
            return Json(await _itemService.GetAllItems(query));
        }
        
        public  IActionResult AddItem()
        {
           var types =  _itemService.GetAllTypes();
           var selectList = new SelectList(types, "Id", "Type");
           ViewBag.Types = selectList;
           return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> AddItem(ItemViewModel itemDto)
        {
            var types = _itemService.GetAllTypes();
            var selectList = new SelectList(types, "Id", "Type");
            ViewBag.Types = selectList;
            if (!ModelState.IsValid) return View();
            var wwwRootPath = _webHostEnvironment.WebRootPath;
            await ImageMapper.MapImage(itemDto, wwwRootPath);
            var item = new Item
            {
                Name = itemDto.Name,
                Price = itemDto.Price,
                Description = itemDto.Description,
                ImageName = itemDto.ImageName,
                TypeId = itemDto.TypeId
            };
            await _itemService.CreateItem(item);
            return Redirect("/Item/Items");
        }
        [HttpGet("[controller]/{itemId}/[action]")]
        public async Task<IActionResult> EditItem([FromRoute]int itemId)
        {
            var item = await _itemService.GetItem(itemId);
            var itemViewModel = new ItemViewModel()
            {
                Id = item.Id,
                Name = item.Name,
                Price = item.Price,
                Description = item.Description,
                ImageName = item.ImageName,
                TypeId = item.TypeId
            };
            
            return View(itemViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditItemPost(ItemViewModel itemDto)
        {
            if (!ModelState.IsValid) return View("EditItem");
            var wwwRootPath = _webHostEnvironment.WebRootPath;
            Item item;
            if (itemDto.ImageFile == null)
            {
                item = new Item
                {
                    Id = itemDto.Id,
                    Name = itemDto.Name,
                    Price = itemDto.Price,
                    Description = itemDto.Description,
                    TypeId = itemDto.TypeId
                };
                await _itemService.UpdateItem(item);
                return Redirect("/Item/Items");
            }
            await ImageMapper.MapImage(itemDto, wwwRootPath);
                
            item = new Item
            {
                Id = itemDto.Id,
                Name = itemDto.Name,
                Price = itemDto.Price,
                Description = itemDto.Description,
                ImageName = itemDto.ImageName,
                TypeId = itemDto.TypeId
            };
            await _itemService.UpdateItem(item);
           return Redirect("/Item/Items");

        }
        
        [HttpDelete("[controller]/{itemId}")]
        public async Task<IActionResult> DeleteItem([FromRoute]int itemId)
        {
            await _itemService.RemoveItem(itemId);
            return Ok();
        }
    }
}

MusicStore.WebApp/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicStore.Business.Interfaces;
using MusicStore.Business.Responses;
using MusicStore.Data;
using MusicStore.WebApp.Models;

namespace MusicStore.WebApp.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;
       
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _userService = userService;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());
 
        public IActionResult Create() => View();
        
        [HttpPost]
        public async Task<IActionResult> Create(CreateRole role)
        {
            if (!ModelState.IsValid) return View();
            var result = await _roleManager.CreateAsync(new IdentityRole(role.Name));
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(role.Name);
        }
         
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
        
        public IActionResult UserList () => View();
        
        [HttpPost]
        public async Task<IActionResult> UserList([FromBody]DtQuery query)
        {
          
            var dbQuery = _userManager.Users.Where(x => x.Email != "admin@mail.ru");
            
            var lowerQ = query.Search?.ToLower();
            if (!string.IsNullOrWhiteSpace(lowerQ))
            {
                dbQuery = (lowerQ?.Split(' ')).Aggregate(dbQuery, (current, searchWord) =>
                    current.Where(f =>
                        f.Surname.ToLower().Contains(searchWord) ||
                        f.Name.ToLower().Contains(searchWord) ||
                        f.Email.ToString().ToLower().Contains(searchWord)
                    ));
            }

            // sorting
            if (!string.IsNullOrWhiteSpace(query.OrderColumn) && !string.IsNullOrWhiteSpace(query.OrderDir))
            {
                dbQuery = query.OrderColumn switch
                {
                    "surname" => (query.OrderDir.Equals("asc"))
                        ? dbQuery.OrderBy(o => o.Surname)
                        : dbQuery.OrderByDescending(o => o.Surname),
                    "name" => (query.OrderDir.Equals("asc"))
                        ? dbQuery.OrderBy(o => o.Name)
                        : dbQuery.OrderByDescending(o => o.Name),
                    "email" => (query.OrderDir.Equals("asc"))
                        ? dbQuery.OrderBy(o => o.Email)
                        : dbQuery.OrderByDescending(o => o.Email),
                    _ => (query.OrderDir.Equals("asc"))
                        ? dbQuery.OrderBy(o => o.Id)
                        : dbQuery.OrderByDescending(o => o.Id)
                };
            }
            
            // total count
            var totalItemCount = dbQuery.Count();

            // paging
            dbQuery = dbQuery.Skip((query.PageNumber - 1) * query.PageSize).Take(query.PageSize);
            
            var dbItems = await dbQuery.ToArrayAsync();
            
            return Json(new PagedResponse<ApplicationUser[]>(dbItems, totalItemCount, query.PageNumber, query.PageSize));
        } 
        [HttpGet("[controller]/{id}/[action]")]
        public async Task<IActionResult> EditRole(string id)
        {
         
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var userRoles = await _userManager.GetRolesAsync(user);
            var allRoles = _roleManager.Roles.ToList();
            var model = new ChangeRoleViewModel
            {
                Id = user.Id,
                UserEmail = user.Email,
                UserRoles = userRoles,
                AllRoles = allRoles
            };
            return View("Edit", model);

        }
        
        [HttpPost]
        public async Task<IActionResult> EditRolePost(string id, List<string> roles)
        {
          
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var userRoles = await _userManager.GetRolesAsync(user);
              
            var allRoles = _roleManager.Roles.ToList();
              
            var addedRoles = roles.Except(userRoles);
              
            var removedRoles = userRoles.Except(roles);
 
            await _userManager.AddToRolesAsync(user, addedRoles);
 
            await _userManager.RemoveFromRolesAsync(user, removedRoles);
 
            return RedirectToAction("UserList");

        }
        [HttpGet("[controller]/{id}/[action]")]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var userViewModel = new UserViewModel()
            {
                Id = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                Address = user.Address
            };
            return PartialView("UserDetails", userViewModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> EditUserPost(ApplicationUser userDto)
        {
            var user = await _userManager.FindByIdAsync(userDto.Id);
            if (!ModelState.IsValid) return View("UserDetails");
            user.Name = userDto.Name;
            user.Surname = userDto.Surname;
            user.Address = userDto.Address;
            await _userManager.UpdateAsync(user);
            return Redirect("/Role/UserList");
        }
        
        [HttpGet("[controller]/{id}/{name}/[action]")]
        public  IActionResult RemoveUser(string id, string name)
        {
            var userViewModel = new UserViewModel()
            {
                Id = id,
                Name = name
            };
            return View("ConfirmDelete", userViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> RemoveUserPost(UserViewModel userDto)
        {
            await _userService.RemoveUser(userDto.Id);
            return Redirect("/Role/UserList");
        }
        
        [HttpGet("[controller]/{id}/[action]")]
        public async Task<IActionResult> ChangePassword(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var passwordModel = new ChangePasswordModel()
            {
                Id = user.Id
            };
            return PartialView(passwordModel);
        }
        public async Task<IActionResult> ChangeAndHashPass(ChangePasswordModel model)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                return NotFound();
            }
            user.PasswordHash = _userManager.PasswordHasher.HashPassword(user, model.Password);
            var result = await _userManager.UpdateAsync(user);
            if (!result.Succeeded)
            {
                return BadRequest();
            }
            return Ok();
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangePasswordPost(ChangePasswordModel model)
        {
            if (!ModelState.IsValid) return View("ChangePassword");
            await  ChangeAndHashPass(model);
            return Redirect("/Role/UserList");
        }
    }   
    }

MusicStore.WebApp/Views/Shared/_Culture.cshtml
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions
@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem {Value = x.Name, Text = Localizer.GetString(x.Name)}).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<div>
    <form asp-action="CultureManagment" asp-controller="Home" method="post"
          asp-route-returnUrl="@returnUrl">
        <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList"
                onchange="this.form.submit();" class="form-control"></select>
    </form>
</div>

MusicStore.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Music Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/validation.css"/>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css"/>


</head>
<body>
<header>
    @if (User.IsInRole("Admin"))
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Admin mode"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Items">@Localizer["Items"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">@Localizer["Roles"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetUnproccessed">@Localizer["Orders"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Finished">@Localizer["Logs"]</a>
                        </li>
                    </ul>
                    <div >
                        <partial name="_Culture"/>
                    </div>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Music Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Items">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetOrders">@Localizer["My orders"]</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark bi bi-cart4" asp-area="" asp-controller="Cart" asp-action="GetCart" id="cart"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visualization" asp-action="Index" id="cart">@Localizer["Top products"]</a>
                        </li>
                    </ul>
                    <div >
                        <partial name="_Culture"/>
                    </div>
                    <partial name="_LoginPartial"/>

                </div>

            </div>
        </nav>
    }

</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Music Store
    </div>

</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script>

$(function () {
    updateCart();
});
</script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>